### ISSUE TITLE
restart-serverの条件

### ISSUE THREAD

**Issue by delihiros** [ayato-p/clojure-beginner#10]
[Part3](http://ayato-p.github.io/clojure-beginner/intro_web_development/part3_what_is_compojure.html
restart-server)にあるユーティリティ関数`restart-server`の定義は以下のようになっていますが、

``` clj
(defn restart-server []
  (when @server
    (stop-server)
    (start-server)))
```

`stop-server`と`start-server`はいずれもサーバが起動しているか否かをチェックしているので、条件をなくして

``` clj
(do (stop-server)
    (start-server))
```

としてはいかがでしょうか。
`restart-server`さえ呼べばサーバが起動するようになるので、便利ではないかと思います。

**Comment by ayato-p** [comment]
おお、ありがとうございます。
確かにそうですね。ただ、その修正を今からするとコードとの乖離が発生するので、ドキュメントの方に注釈でも付けて対応しようと思います :)
